
development:
    key: 786bb4519bc7f2b2304e866de0a0b93d
    secret: 1b9950caa92826ca527d1bcf6907b3f0
    canvas_path: /golfbookapp_dev/
    callback_path: /
    tunnel:
      username: yourLoginName
      host: www.yourexternaldomain.com
      port: 1234
      local_port: 5678

test:
    key: 838e3b71f1bb2379bb1da00638db020e
    secret: 1fdad4d4f084741b8d588f3c1130988d
    canvas_path: /golfbookapp/
    callback_path: /
    tunnel:
      username: yourLoginName
      host: www.yourexternaldomain.com
      port: 1234
      local_port: 5678

production:
    key: 838e3b71f1bb2379bb1da00638db020e
    secret: 1fdad4d4f084741b8d588f3c1130988d
    canvas_path: /golfbookapp/
    callback_path: /
    tunnel:
      username: yourLoginName
      host: www.yourexternaldomain.com
      port: 1234
      local_port: 5678
