--- 
development: 
  photo_added: "72936236275"
  caddy_rated: 
  course_rated: 
  round_posted: 
  asset_identified: "72949966275"
  caddy_added: 
  course_added: 
production: 
  photo_added: 
  caddy_rated: 
  course_rated: 
  round_posted: 
  caddy_added: 
  course_added: 
staging: 
  photo_added: 
  caddy_rated: 
  course_rated: 
  round_posted: 
  caddy_added: 
  course_added: 
